export const PRODUCT_KEYWORDS = [
  "deformed bar",
  "rebar",
  "steel supplier",
  "construction materials",
  "angle bar",
  "flat bar",
  "round bar",
  "steel plate",
  "ms plate",
  "gi pipe",
  "bi pipe",
  "square tube",
  "rectangular tube",
  "c purlin",
  "steel grating",
  "cyclone wire",
  "welded wire mesh",
  "anchor bolt",
  "stud bolt",
  "long span roofing",
  "sheet pile",
  "wide flange",
  "i beam",
] as const;

export const BUYER_INTENT_PHRASES = [
  "looking for",
  "lf:",
  "lf ",
  "need supplier",
  "supplier needed",
  "any supplier",
  "need quotation",
  "request for quotation",
  "rfq",
  "pa quote",
  "pa-quote",
  "please quote",
  "quote please",
  "naghahanap",
  "hanap supplier",
  "pahanap",
  "kailangan po",
  "may supplier ba",
  "may nagbebenta ba",
  "saan makakabili",
  "where to buy",
  "want to buy",
  "wanted:",
  "need price",
  "pa presyo",
  "need materials",
  "looking to purchase",
  "canvassing",
] as const;

export const SELLER_ONLY_PHRASES = [
  "are you looking",
  "do you need",
  "still looking",
  "we supply",
  "we can supply",
  "we are a supplier",
  "we are direct supplier",
  "we sell",
  "we offer",
  "we are offering",
  "we're offering",
  "we offering",
  "we can offer",
  "we provide",
  "we can provide",
  "our products",
  "our services",
  "we deliver",
  "we fabricate",
  "we manufacture",
  "available stocks",
  "available stock",
  "stocks available",
  "now available",
  "ready stock",
  "ready for delivery",
  "in stock",
  "on hand stocks",
  "on hand stock",
  "for sale",
  "pm for orders",
  "dm for orders",
  "open for orders",
  "accepting orders",
  "order now",
  "place your order",
  "message us for quotation",
  "message us for price",
  "send us a message",
  "contact us for",
  "call us now",
  "free delivery",
  "nationwide delivery",
  "wholesale and retail",
  "wholesale price",
  "promo price",
  "special offer",
  "limited offer",
  "get yours now",
  "direct supplier here",
  "your trusted supplier",
] as const;

export const DEFAULT_PLATFORM_DOMAINS = [
  "facebook.com",
  "instagram.com",
  "threads.com",
  "tiktok.com",
  "linkedin.com",
  "reddit.com",
] as const;

export const PH_LOCATION_HINTS = [
  "metro manila",
  "manila",
  "quezon city",
  "makati",
  "pasig",
  "taguig",
  "paranaque",
  "valenzuela",
  "caloocan",
  "bulacan",
  "cavite",
  "laguna",
  "rizal",
  "batangas",
  "pampanga",
  "tarlac",
  "nueva ecija",
  "pangasinan",
  "lucena",
  "bataan",
  "zambales",
] as const;
