export const PRODUCT_KEYWORDS = [
  "deformed bar",
  "rebar",
  "steel supplier",
  "construction materials",
  "angle bar",
  "flat bar",
  "round bar",
  "steel plate",
  "ms plate",
  "gi pipe",
  "bi pipe",
  "square tube",
  "rectangular tube",
  "c purlin",
  "steel grating",
  "cyclone wire",
  "welded wire mesh",
  "anchor bolt",
  "stud bolt",
  "long span roofing",
  "sheet pile",
  "wide flange",
  "i beam",
] as const;

export const BUYER_INTENT_PHRASES = [
  "looking for",
  "need supplier",
  "supplier needed",
  "need quotation",
  "request for quotation",
  "rfq",
  "pa quote",
  "pa-quote",
  "naghahanap",
  "saan makakabili",
  "where to buy",
  "need price",
  "need materials",
  "looking to purchase",
  "canvassing",
] as const;

export const SELLER_ONLY_PHRASES = [
  "we supply",
  "we deliver",
  "available stocks",
  "for sale",
  "pm for orders",
  "message us for quotation",
  "direct supplier here",
] as const;

export const DEFAULT_PLATFORM_DOMAINS = [
  "facebook.com",
  "instagram.com",
  "threads.com",
  "tiktok.com",
  "linkedin.com",
  "reddit.com",
] as const;

export const PH_LOCATION_HINTS = [
  "metro manila",
  "manila",
  "quezon city",
  "makati",
  "pasig",
  "taguig",
  "paranaque",
  "valenzuela",
  "caloocan",
  "bulacan",
  "cavite",
  "laguna",
  "rizal",
  "batangas",
  "pampanga",
  "tarlac",
  "nueva ecija",
  "pangasinan",
  "lucena",
  "bataan",
  "zambales",
] as const;
